// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegisterWebAPI.Models;

namespace RegisterWebAPI.Migrations.Roster
{
    [DbContext(typeof(RosterContext))]
    partial class RosterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegisterWebAPI.Models.Roster", b =>
                {
                    b.Property<int>("PMId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tag1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tag2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tag3")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tag4")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tag5")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tag6")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PMId");

                    b.ToTable("RosterChamps");
                });
#pragma warning restore 612, 618
        }
    }
}
