// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegisterWebAPI.Models;

namespace RegisterWebAPI.Migrations.StaticChamp
{
    [DbContext(typeof(StaticChampContext))]
    partial class StaticChampContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegisterWebAPI.Models.StaticChamp", b =>
                {
                    b.Property<int>("PMId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Assassin");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Fighter");

                    b.Property<bool>("Mage");

                    b.Property<bool>("Marksman");

                    b.Property<bool>("Support");

                    b.Property<bool>("Tank");

                    b.HasKey("PMId");

                    b.ToTable("StaticChamps");
                });
#pragma warning restore 612, 618
        }
    }
}
